title: Project
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  extra:
    label: Extra
    text: text
  text:
    label: Text
    type:  textarea

  imgFirst:
    label: Mobile image first
    type: toggle
